fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.10.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.3.2"
  repositories:
  symlinks:
    puppet_redbox: "#{source_dir}"