fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.7.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.3.2"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.0.2"  
    apache:
      repo: "puppetlabs/apache"
      ref: "1.1.1"
  repositories:
    puppet_common:
      repo: "git://github.com/redbox-mint-contrib/puppet_common"
      ref: "master"
  symlinks:
    puppet_redbox: "#{source_dir}"