language: ruby
rvm:
 - "1.9.3"
 - "2.0.0-p598"
 - "2.0.0"
sudo: required
services:
 - docker
env:
 - PUPPET_VERSION="3.8.4"
script:
 - rake validate
 - rake lint
 - rake spec_coverage
 - travis_wait rake beaker
