language: ruby
rvm:
 - "1.8.7"
 - "1.9.3"
 - "2.0.0-p598"
 - "2.0.0"
 - "2.1.4"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
env:
 - PUPPET_VERSION="3.8.4"
task: default => [:spec, :lint]
