language: ruby
rvm:
 - "1.9.3"
 - "2.0.0-p598"
 - "2.0.0"
sudo: required
services:
 - docker
env:
 - PUPPET_VERSION="3.8.4"
 - TEST_SUITE="rake validate"
 - TEST_SUITE="rake lint"
 - TEST_SUITE="rake spec_coverage"
 - TEST_SUITE="export BEAKER_set='default'; rake beaker"
 - TEST_SUITE="export BEAKER_set='centos7-64'; rake beaker"
script:
 - $TEST_SUITE
