language: ruby
rvm:
 - "1.9.3"
 - "2.0.0-p598"
 - "2.0.0"
sudo: required
services:
 - docker
env:
  global:
    - PUPPET_VERSION="3.8.4"
  matrix:
    - TEST_SUITE="rake validate && rake lint && rake spec_coverage"
    - TEST_SUITE="BEAKER_set=default && rake beaker"
    - TEST_SUITE="BEAKER_set=centos7-64 && rake beaker"
script:
 - $TEST_SUITE